### ISSUE TITLE
Missing data download for NLTK processors

### ISSUE THREAD

**Issue by jennyzhang-petuum** [asyml/forte-wrappers#19]
**Describe the bug**
Missing data download for NLTK processors 
For example, the required data need to be download before using NLTK processors are `punkt`, `averaged_perceptron_tagger`, `wordnet`, `maxent_ne_chunker`, `words`.

**Comment by hunterhector** [comment]
close because duplicated with https://github.com/asyml/forte-wrappers/issues/22
