### ISSUE TITLE
Base64 discrepancy in elastic search 7.5.1 with Python 3.9.x

### ISSUE THREAD

**Issue by Piyush13y** [asyml/forte-wrappers#84]
**Describe the bug**
Elasticsearch uses decodestring from base64 library in its version = 7.5.1 (the version required by the setup file in forte.elastic)
However, decodestring has been a deprecated alias of decodebytes since Python 3.1 and has been completely removed since Python 3.9. Hence, while using Python3.9.x, trying to import forte.elastic throws an error:
`ImportError: cannot import name 'decodestring' from 'base64'`

**To Reproduce**
Run any example that consumes forte.elastic module on Python 3.9.x

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS Monterey M1
 - Python and Package versions: Python 3.9.7

**Possible solution**
Use an updated version of elastic search in forte->requirements as well as in forte-wrappers->elastic

**Comment by Piyush13y** [comment]
I can go ahead and raise the fix for this. However, I am unable to assign this issue to myself. 

I see that a few examples do use `fortex.elastic` to create an indexer to make search faster in their flow. Do we not need this anymore? To be able to remove the `elasticsearch` dependency?

**Comment by hunterhector** [comment]
Thanks, I just assigned you to the ticket.

As for the docs/requirements, as long as the docs build successfully, we don't have to worry about the dependency.

As for those examples in Forte, they are not Forte requirements. Those examples can be considered as projects that use "forte-wrapper" and "forte", so the dependency finally comes back to forte-wrappers
