### ISSUE TITLE
No module named 'ftx.medical' in spacy/spacy_processors.py

### ISSUE THREAD

**Issue by Xuezhi-Liang** [asyml/forte-wrappers#92]
**Describe the bug**
This bug occurs when running the forte blog_post_example. Just because refactor the forte medical module. 
So need to modify 
```python

from ftx.medical import MedicalEntityMention, UMLSConceptLink
```
to
```python
from ftx.onto.clinical import MedicalEntityMention, UMLSConceptLink
```
in spacy/spacy_processors.py
**To Reproduce**
1. P epare data `...`
2. R n command '....'
3. S e error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11881183/156157905-f0435433-16d9-417b-bd26-303c474f9f43.png)

**Environment (please complete the following information):**
 - Python and Package verions: [e.g. Python version, Pytorch version]

**Additional context**

**Comment by hunterhector** [comment]
close since duplicated with https://github.com/asyml/forte-wrappers/issues/87
