### ISSUE TITLE
ModuleNotFoundError: No module named 'ftx.medical'

### ISSUE THREAD

**Issue by munachisonwadike** [asyml/forte-wrappers#98]
Hello! 
 **Issue**
When I try to run the composable information system's cordindexer, mentioned [here](https://github.com/petuum/composing_information_system/blob/main/QA.md) i.e `python examples/pipeline/indexer/cordindexer.py --data-dir ../cord_data_2021-04-13/document_parses/pdf_json`, I get an error `ModuleNotFoundError: No module named 'ftx.medical'`
What may this mean? Would it be an issue with the forte-wrappers? Is ftx a different alias for forte-wrappers?
Warm regards,
**Screenshots**
![image](https://user-images.githubusercontent.com/22077758/158037028-2c958ccc-67d3-4910-81f7-31fba47ef711.png)

**Comment by hunterhector** [comment]
We have recently reorganize some package names here: https://github.com/asyml/forte/blob/master/ftx/onto/clinical.py, probably I can go ahead and change these references.
